Create3 Addition
rahulanonymous/xsafe_create2 pull request #9
Opened 2023-11-01 01:26 UTC by cucupac

2023-11-01 04:40 UTC, rahul0eth approved these changes

2023-11-02 02:53 UTC, 0xernesto requested changes

2023-11-02 02:53 UTC, 0xernesto commented on script/Create3Factory.s.sol
> +pragma solidity ^0.8.13;
Should delete the entire script directory, since there is nothing relevant in there right now.

2023-11-02 02:53 UTC, 0xernesto commented on src/create2/interfaces/ICreate2Factory.sol
> +interface ICreate2Factory {
Consider reordering these to match the order of functions in the contract, similar to the ICreate3Factory interface.

2023-11-02 03:29 UTC, 0xernesto approved these changes

2023-11-02 03:32 UTC, rahul0eth approved these changes

2023-11-02 03:36 UTC, merged